# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: atlas
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    tap:
      owner: codeatlas3
      name: atlas
    commit_author:
      name: Mohanasundaram N
      email: codewithmohanasundaram@gmail.com
    folder: Formula
    homepage: "https://github.com/codeatlas3/atlas"
    description: "Atlas is an opinionated CLI to generate Golang microservice and Flutter application"
    license: "Apache 2.0"
    install: |
      bin.install "atlas"