# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlas < Formula
  desc "Atlas is an opinionated CLI to generate Golang microservice and Flutter application"
  homepage "https://github.com/codeatlas3/atlas"
  version "0.0.3-alpha"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeatlas3/atlas/releases/download/0.0.3-alpha/atlas_0.0.3-alpha_Darwin_x86_64.tar.gz"
      sha256 "16b3303c7ccea2c08b86424b38180716ceb479a20daa23fc292deaba06e9aa38"
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeatlas3/atlas/releases/download/0.0.3-alpha/atlas_0.0.3-alpha_Darwin_arm64.tar.gz"
      sha256 "49f537cd5dcb057ae7ef010148b280db30601853bf68600286da40f5b28c4f4e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/codeatlas3/atlas/releases/download/0.0.3-alpha/atlas_0.0.3-alpha_Linux_x86_64.tar.gz"
      sha256 "f6a1b85524165f3d54cc6dbbf226e6f2e53a4562800d27f8bc302b670b9bf275"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codeatlas3/atlas/releases/download/0.0.3-alpha/atlas_0.0.3-alpha_Linux_arm64.tar.gz"
      sha256 "ed3ee3d950eb4ce34384263cf725228f62f716334eb2ba79bb34b3b35be88065"
    end
  end

  def install
    bin.install "atlas"
  end
end
