# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlas < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://example.com/"
  version "0.0.2-alpha"
  license "Apache-2.0 License"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeatlas3/atlas/releases/0.0.2-alpha/atlas_0.0.2-alpha_Darwin_x86_64.tar.gz"
      sha256 "13b5f14efa1b3e608ca06ba4291ca4ddfcf18f38891dd216b5addf6d945a12a4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeatlas3/atlas/releases/0.0.2-alpha/atlas_0.0.2-alpha_Darwin_arm64.tar.gz"
      sha256 "e9c731f8438935e403554dd5eda7b7008a2799839212bb766a4f5feb339e7139"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/codeatlas3/atlas/releases/0.0.2-alpha/atlas_0.0.2-alpha_Linux_x86_64.tar.gz"
      sha256 "2dcc9c5a3ef94b23e33c80aadcdf1d5720664cae85f125023198d7219b99b052"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codeatlas3/atlas/releases/0.0.2-alpha/atlas_0.0.2-alpha_Linux_arm64.tar.gz"
      sha256 "49e7f18d82986d77ffa4f9249640cfb8aafbeb9c1d14b0ee02541ca0d88420b5"
    end
  end

  depends_on "git"
  depends_on "zsh" => :optional

  conflicts_with "svn"
  conflicts_with "bash"

  def install
    bin.install "program"
    ...
  end

  def post_install
    etc.install "app-config.conf"
...

  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/program --version"
    ...
  end
end
