# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlas < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://example.com/"
  version "0.0.1-alpha"
  license "Apache-2.0 License"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeatlas3/atlas/releases/0.0.1-alpha/atlas_0.0.1-alpha_Darwin_x86_64.tar.gz"
      sha256 "7aa677c8c14b4fa6365271fc90763d4a18902631357ba93db4b0c7d014d918ab"
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeatlas3/atlas/releases/0.0.1-alpha/atlas_0.0.1-alpha_Darwin_arm64.tar.gz"
      sha256 "cf6baf7571ff49167c2b54cef39bc9f7a4055cd03d82f9e87dfe92eb242ed56e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/codeatlas3/atlas/releases/0.0.1-alpha/atlas_0.0.1-alpha_Linux_x86_64.tar.gz"
      sha256 "a7bb932eafc46db8e1b5822b4af098858fe50a88db93992d34cfa4dcf91d142f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codeatlas3/atlas/releases/0.0.1-alpha/atlas_0.0.1-alpha_Linux_arm64.tar.gz"
      sha256 "5d1a93ee0e516bd39827384c2218f88f05358915e48613828e6e35986a911656"
    end
  end

  depends_on "git"
  depends_on "zsh" => :optional

  conflicts_with "svn"
  conflicts_with "bash"

  def install
    bin.install "program"
    ...
  end

  def post_install
    etc.install "app-config.conf"
...

  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/program --version"
    ...
  end
end
